from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from typing import Any

from app.benchmark_registry import SQLITE_ROOTS, find_benchmark_gold_sql, get_schema_context
from app.config import get_settings
from app.gemini import GeminiService
from app.gemini.schemas import GeminiConfigError, QueryPlanParseError
from app.nl2ir.provider import get_nl2ir_provider
from app.nl2ir.schemas import NL2IRRequest
from app.simple_nl2sql import build_simple_schema_nl2sql
from app.tools.schemas import DatasetContext

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ResolvedSQL:
    sql: str | None
    explanation: str
    provider: str


def resolve_sql_for_message(
    message: str,
    context: DatasetContext,
    schema: dict[str, Any] | None = None,
) -> ResolvedSQL:
    """Resolve NL questions to SQL using the same provider priority as the plan pipeline."""
    if schema is None and context.dbType == "sqlite_benchmark" and context.benchmark and context.dbId:
        schema = get_schema_context(context.benchmark, context.dbId)

    if _should_use_gemini():
        resolved = _resolve_with_gemini(message, schema)
        if resolved:
            return resolved

    if context.benchmark in SQLITE_ROOTS and context.dbId:
        resolved = _resolve_with_nl2ir(message, context, schema)
        if resolved:
            return resolved

    if context.benchmark and context.dbId:
        gold_sql = find_benchmark_gold_sql(context.benchmark, context.dbId, message)
        if gold_sql:
            return ResolvedSQL(
                sql=gold_sql,
                explanation=f"Matched a known {context.benchmark} benchmark question.",
                provider="gold_sql",
            )

    if schema:
        fallback = build_simple_schema_nl2sql(message, schema)
        if fallback:
            has_filters = bool(fallback.intent_ir.get("filters"))
            if not needs_real_nl2sql(message) or has_filters:
                return ResolvedSQL(
                    sql=fallback.sql,
                    explanation=fallback.explanation,
                    provider="simple_fallback",
                )

    return ResolvedSQL(sql=None, explanation="", provider="none")


def needs_real_nl2sql(message: str) -> bool:
    """Return True when a single-table demo fallback would likely misread the question."""
    text = message.lower().strip()
    if re.search(r"""['"].+['"]""", message):
        return True
    if re.search(r"\b(where|named|called|specific|filter|join|whose|belonging to)\b", text):
        return True
    if re.search(r"\b(is|are|equals?|equal to)\s+[\w]", text):
        return True
    if re.search(r"\b(by|for|from|with)\s+(the\s+)?(artist|author|customer|user|player|team)\b", text):
        return True
    return False


def _should_use_gemini() -> bool:
    settings = get_settings()
    return (
        settings.query_plan_provider.lower() == "gemini"
        and bool(settings.gemini_api_key.strip())
    )


def _resolve_with_gemini(message: str, schema: dict[str, Any] | None) -> ResolvedSQL | None:
    service = GeminiService()
    if not service.is_configured:
        return None
    try:
        plan = service.generate_query_plan(message, schema)
    except (GeminiConfigError, QueryPlanParseError, TimeoutError, RuntimeError) as exc:
        logger.warning("Gemini SQL resolution failed: %s", exc)
        return None
    if not plan.sql:
        return None
    explanation = plan.goal.strip() if plan.goal else "Generated with Gemini from your question and schema."
    return ResolvedSQL(sql=plan.sql, explanation=explanation, provider="gemini")


def _resolve_with_nl2ir(
    message: str,
    context: DatasetContext,
    schema: dict[str, Any] | None,
) -> ResolvedSQL | None:
    try:
        result = get_nl2ir_provider().generate_ir(
            NL2IRRequest(
                message=message,
                schema_context=schema,
                dataset_context=context.model_dump(),
            )
        )
    except Exception as exc:  # noqa: BLE001 - provider failures should fall through to other resolvers.
        logger.warning("NL2IR SQL resolution failed: %s", exc)
        return None
    if not result or not result.selected_sql:
        return None
    explanation = "Generated by the KDDCup data-agent from your question and database schema."
    if result.provider_name == "kddcup":
        explanation = (
            "Generated by the KDDCup agent after inspecting the database schema and relationships."
        )
    return ResolvedSQL(sql=result.selected_sql, explanation=explanation, provider=result.provider_name)
