// ================================================
// DebugSQL – Chat / AI Query API  (Phase 7)
//
// Typed request/response models and API functions for the chat endpoint.
// These functions are NOT called yet — the mock is used via chatAdapter.ts.
// Swap in these functions when the real backend is ready.
//
// Target endpoints:
//   POST /api/query          → send a natural-language query
//   GET  /api/sessions/:id/messages → load persisted chat history
// ================================================

import { apiGet, apiPost } from './client';
import type { RequestOptions } from './client';

// ---- Request types ----

export interface ChatQueryRequest {
  /** The natural-language message typed by the user. */
  message:   string;
  /** Active session ID for conversation continuity. */
  sessionId: string;
}

// ---- Response types ----

export interface ChatQueryResponse {
  /** The assistant's markdown response text. */
  content:      string;
  /**
   * ID of the query plan generated by the backend.
   * Used to load the plan graph via getQueryPlan().
   */
  planId:       string;
  /** Generated SQL, if the backend exposes it directly. */
  sql?:         string;
  /** Human-readable explanation of the plan choices. */
  explanation?: string;
}

/** Single persisted message from server-side session history. */
export interface SessionMessage {
  id:        string;
  role:      'user' | 'assistant';
  content:   string;
  timestamp: string;
  planId?:   string;
}

// ---- API functions ----

/**
 * POST /api/query
 *
 * Sends a natural-language query to the backend AI pipeline.
 * Returns the assistant's response, generated SQL, and a planId
 * that can be used to fetch the full query plan graph.
 *
 * TODO: Replace mock adapter with this real backend API call
 * TODO: Connect websocket/live execution updates for streaming responses
 */
export async function postChatQuery(
  body:     ChatQueryRequest,
  options?: RequestOptions,
): Promise<ChatQueryResponse> {
  return apiPost<ChatQueryResponse>('/query', body, options);
}

/**
 * GET /api/sessions/:sessionId/messages
 *
 * Loads the persisted chat history for a session.
 * Called on page load to restore previous conversation state.
 *
 * TODO: Persist query history — load previous messages on session restore
 * TODO: Integrate authentication/session handling
 */
export async function getSessionMessages(
  sessionId: string,
  options?:  RequestOptions,
): Promise<SessionMessage[]> {
  return apiGet<SessionMessage[]>(`/sessions/${sessionId}/messages`, options);
}
